#! /bin/sh

NEW_PULSES="/tmp/GIT-NEW/"

PULSES_SOURCE="/home/dada/PULSES_i5/pulses/"
PULSES_NAME="pulses/"

SOFTBOARD_SOURCE="/home/dada/ARDUINO-GIT2/softboard/"
SOFTBOARD_TMP="/tmp/SOFTBOARD"
SOFTBOARD_NAME="$SOFTBOARD_TMP/softboard/"


# start all over again...
rm -rf $NEW_PULSES
rm -rf $SOFTBOARD_TMP

echo "Building new pulses git repository in $NEW_PULSES."
mkdir -p $NEW_PULSES || exit 1
cd $NEW_PULSES || exit 1
# pwd ; ls -Al

echo "Clone $PULSES_SOURCE to $(pwd):"
git clone $PULSES_SOURCE || exit 1
# ls -A1

# cd $PULSES_NAME || exit 1
# pwd ; ls -Al
#
# echo "Remove remote origin in pulses."
# git remote rm origin

echo "Clone softboard to temporary location $SOFTBOARD_TMP."
mkdir $SOFTBOARD_TMP
cd $SOFTBOARD_TMP || exit 1

git clone $SOFTBOARD_SOURCE || exit 1
#pwd ; ls -A1

cd $SOFTBOARD_NAME || exit 1
# pwd ; ls -Al
#
echo "Remove remote origin in softboard."
git remote rm origin

echo "Move README and commit that."
git mv README softboard/README
git commit -m "Softboard c-version as base for Menu example."


echo "Merge softboard repo into pulses."
cd $NEW_PULSES || exit 1
cd $PULSES_NAME || exit 1
# pwd ; ls -Al

git remote add -f softb $SOFTBOARD_NAME
git merge --no-commit softb/master
#git read-tree --prefix=softboard/ -u softb/master
#git read-tree softb/master
git commit -m "Merged c softboard version as basis for examples."
git pull -s subtree softb master
git remote rm softb
pwd ; ls -Al

mkdir -p libraries/Menu/examples/softboard/ || exit 1
git mv softboard/* libraries/Menu/examples/softboard/
git commit -m "Moved c softboard version to examples/softboard"
rmdir softboard

git status
