#! /bin/sh
  #! /bin/sh
  # ****************************************************************
  # Script used to merge the old softboard repo into pulses:
  # indented to leave #comments when included in commit message...
  # ****************************************************************
  
  GIT_REPO_DIR="/home/dada/PULSES_i5/"
  PULSES_SOURCE="${GIT_REPO_DIR}pulses/"
  PULSES_NAME="pulses/"
  
  SOFTBOARD_SOURCE="/home/dada/ARDUINO-GIT2/softboard/"
  SOFTBOARD_TMP="/tmp/SOFTBOARD"
  SOFTBOARD_NAME="$SOFTBOARD_TMP/softboard/"
  
  # ****************************************************************
  # start all over again...
  rm -rf $NEW_PULSES
  rm -rf $SOFTBOARD_TMP
  
  
  # ****************************************************************
  echo "Clone softboard to temporary location $SOFTBOARD_TMP."
  mkdir $SOFTBOARD_TMP
  cd $SOFTBOARD_TMP || exit 1
  
  git clone $SOFTBOARD_SOURCE || exit 1
  #pwd ; ls -A1
  
  cd $SOFTBOARD_NAME || exit 1
  # pwd ; ls -Al
  #
  
  
  # ****************************************************************
  echo "Remove remote origin in softboard."
  git remote rm origin
  
  
  # ****************************************************************
  echo "Move README and commit that."
  git mv README softboard/README

  git commit -m "Merge softboard c-version as base for later Menu example.
  
  Preparing repository merge: Do not use.
  
  git mv README softboard/README
  git commit
  ****************************************************************
  ****************************************************************
  "

  ****************************************************************
  
  echo "INCLUDE ${0##*/} SCRIPT
BY HAND IN COMMIT MESSAGE, please."
  sleep 4
  git commit --amend
  
  # ****************************************************************
  echo "Merge softboard repo into pulses."
  cd $PULSES_SOURCE || exit 1
  # pwd ; ls -Al
  # git status

  echo "Working DIRECTLY ON LOCAL REPO ${PULSES_SOURCE}${PULSES_NAME}:"
  echo "Backup ${PULSES_SOURCE}${PULSES_NAME}"
  dated-backup-copy ${PULSES_SOURCE}

  emacs ..	# check and last chance to quit ;)

  git remote add -f softb $SOFTBOARD_NAME
  git merge --no-commit softb/master

  git commit -m "Merged c softboard version.
  
  Transition: Do not use.
  
  git remote add -f softb $SOFTBOARD_NAME
  git merge --no-commit softb/master
  git commit
  "
  
  git pull -s subtree softb master
  git remote rm softb
  #pwd ; ls -Al
  
  
  # ****************************************************************
  echo "Moving to examples/softboard"
  mkdir -p libraries/Menu/examples/softboard/ || exit 1
  git mv softboard/* libraries/Menu/examples/softboard/

  git commit -m "Moved to examples/softboard
  
  mkdir -p libraries/Menu/examples/softboard/ || exit 1
  git mv softboard/* libraries/Menu/examples/softboard/
  git commit
  "
  
  rmdir softboard
  #git status

  echo "done"
  echo
  git status
